### ISSUE TITLE
Property name code-completion not working in some cases

### ISSUE THREAD

**Issue by agudian** [mapstruct/mapstruct-eclipse#14]
Doesn't work, if:
- it's an enum mapping method
- the method has an `@MappingTarget` parameter
- there's an `@TargetType` parameter
- there are multiple source parameters

**Comment by gunnarmorling** [comment]
@agudian Can we close this now? Or is there anything left to be done?

**Comment by agudian** [comment]
Can be closed. Thanks for merging! :-)
