### ISSUE TITLE
Jenkins down

### ISSUE THREAD

**Issue by Balzebub** [mapstruct/mapstruct-eclipse#36]
The Eclipse download seems offline. There's only a message that says jenkins is hybernated.

**Comment by gunnarmorling** [comment]
Thanks for the report! It's up again.

**Comment by gunnarmorling** [comment]
That said, we really need to look into providing a proper update site and/or putting the plug-in to the Eclipse market place.

Should you have any feedback or feature requests on the plug-in, please let us know.
