### ISSUE TITLE
Eclipse Marketplace listing

### ISSUE THREAD

**Issue by wetzer** [mapstruct/mapstruct-eclipse#4]
We definitely should think about to list a more mature version of the MapStruct plug-in on the Eclipse Marketplace.

**Comment by gunnarmorling** [comment]
Yes, that'd be great. Maybe we can do it at the time of the MapStruct 1.0 Final (roughly scheduled for the end of Q1)?

**Comment by wetzer** [comment]
Yes , sounds good!

**Comment by agudian** [comment]
We have it for a while now: https://marketplace.eclipse.org/content/mapstruct-eclipse-plugin
