### ISSUE TITLE
Eclipse neon 3 plugin

### ISSUE THREAD

**Issue by tokazio** [mapstruct/mapstruct-eclipse#42]
Can't install:
![problem occurred_2](https://user-images.githubusercontent.com/7676865/28071038-24b6ab4e-664f-11e7-83db-8ffe4a917896.jpg)

Content.xml not exists

**Comment by agudian** [comment]
I just tried it out, installed a fresh Eclipse and installed the MapStruct plugin via the Marketplace (which points to the URL in your screenshot). Worked like a charm. 
Could that have been a temporary issue with dl.bintray.com? Or your systems certificate chain? Maybe an outdated Java version? Or a proxy within your internet connection?
Try downloading the https://dl.bintray.com/mapstruct/mapstruct-eclipse-site/content.jar from a browser that takes certificates seriously (Chrome or Firefox, for example), to rule out most of the above.

**Comment by agudian** [comment]
Oh and there is indeed no content.xml, as it's included in the content.jar - looking for the content.xml is probably a fallback attempt as the download of the content.jar didn't succeed.

**Comment by tokazio** [comment]
Thanks @agudian 
Yes it's a proxy issue. Is there a zip version womewhere that i can manually install?

**Comment by agudian** [comment]
No, but you can just pull this repository and build it with `mvn clean install` to create the files in org.mapstruct.eclipse.repository/target/repository. The current master contains the same state as published on the update site.
I’ll close this issue now, but feel free to continue commenting or reopen if necessary.

**Comment by tokazio** [comment]
ok thanks @agudian

**Comment by filiphr** [comment]
@agudian, maybe we can upload the zip packages in the GitHub releases section.

**Comment by tokazio** [comment]
ok i've downloaded the files/structures to a local folder then launched a mongoose http server to provide a  http access without the proxy interferences.... fine. Thanks all
