### ISSUE TITLE
Eclipse 2018-12RC1 - incremental compilation fails with APT

### ISSUE THREAD

**Issue by igorzep** [mapstruct/mapstruct-eclipse#43]
Eclipse 2018-12RC1 run on OpenJDK 11. Target project is Java 8 or Java 11. I guess any target will work the same.

In pom.xml:
		<m2e.apt.activation>jdt_apt</m2e.apt.activation>

		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-jdk8</artifactId>
			<version>1.2.0.Final</version>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-processor</artifactId>
			<version>1.2.0.Final</version>
			<scope>provided</scope>
		</dependency>

When I change any of a mapped class or a mapping interface the interface gets error marker with the stack trace below:

Internal error in the mapping processor: java.lang.RuntimeException: javax.annotation.processing.FilerException: Source file already exists : test.mapstruct.TestMapperImpl  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:71)  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.writeToSourceFile(MapperRenderingProcessor.java:52)  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:42)  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.process(MapperRenderingProcessor.java:37)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:280)  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:260)  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:226)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:162)  	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)  	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)  	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:174)  	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)  	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:940)  	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)  	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)  	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)  	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:371)  	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)  	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.incrementalBuildLoop(IncrementalImageBuilder.java:186)  	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:143)  	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:281)  	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:202)  	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)  	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)  	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)  	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)  	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)  	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)  	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)  	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)  	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)  	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)  	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)  	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)  Caused by: javax.annotation.processing.FilerException: Source file already exists : test.mapstruct.TestMapperImpl  	at org.eclipse.jdt.internal.apt.pluggable.core.filer.IdeFilerImpl.createSourceFile(IdeFilerImpl.java:177)  	at org.mapstruct.ap.internal.processor.MapperRenderingProcessor.createSourceFile(MapperRenderingProcessor.java:68)  	... 33 more

**Comment by igorzep** [comment]
Closing as it works well on Eclipse 2018-12 GA

**Comment by filiphr** [comment]
Thanks for letting us know. Seems like it was some kind of a bug in Eclipse

**Comment by philippecade** [comment]
We have this issue with Eclipse 2019-12 _sometimes_. Some builds go through without errors, others show the same error as in the first note.

We're using Eclipse 2019-12 and Mapstruct 1.3.1.Final.

**Comment by filiphr** [comment]
Have a look at my comments in https://github.com/mapstruct/mapstruct/issues/2025#issuecomment-590081932
