### ISSUE TITLE
Eclipse 2019-12 - incremental compilation fails with APT

### ISSUE THREAD

**Issue by hocine68** [mapstruct/mapstruct-eclipse#45]
We're using Eclipse 2019-12 and Mapstruct 1.3.1.Final.
Same issue as #43 
This seems related to ecj compiler since we have the same issue with intellij when using ecj compiler instead of the javac compiler.
This issue is really annoying since we have to rebuild the whole project each time that we have a new mapping with mapstruct.

**Comment by sbespalov** [comment]
I have the same error with Mapstruct 1.3.1.Final and Eclipse 2019-09. 
Also I still have [#1716](https://github.com/mapstruct/mapstruct/issues/1716).

**Comment by filiphr** [comment]
I have already provided an answer https://github.com/mapstruct/mapstruct/issues/2025#issuecomment-590081932.

Please do not cross post the same issue.

Verify that your poms have 

```
<m2e.apt.activation>jdt_apt</m2e.apt.activation>
```

and that the m2e-apt plugin is installed.

**Comment by filiphr** [comment]
@sbespalov please share your entire stacktrace for the issue in https://github.com/mapstruct/mapstruct/issues/1716

**Comment by sbespalov** [comment]
@filiphr thanks for response, stacktrace shared.
