### ISSUE TITLE
Unable to install MapStruct plugin for Eclipse

### ISSUE THREAD

**Issue by Rui-Borralho** [mapstruct/mapstruct-eclipse#46]
Hello,

I am trying to install the plugin for Eclipse and when I try to install, an error message appears saying "No repository found at https://dl.bintray.com/mapstruct/mapstruct-eclipse-site/." This happens when I install with the Eclipse Marketplace and also when Idrag the image to eclipse.

**Comment by filiphr** [comment]
This is a really good point @Rui-Borralho. We completely forgot that the eclipse artifacts are on Bintray. I'll try to build this and create a new release somewhere else

**Comment by i2scam** [comment]
> This is a really good point @Rui-Borralho. We completely forgot that the eclipse artifacts are on Bintray. I'll try to build this and create a new release somewhere else

@filiphr any news on this issue?

**Comment by filiphr** [comment]
You can now use https://mapstruct.org/eclipse/ for getting the plugin. We are working on updating the Eclipse Marketplace

**Comment by filiphr** [comment]
We have also updated the link on the [Eclipse Marketplace](https://marketplace.eclipse.org/content/mapstruct-eclipse-plugin). If there are still issues please let us know

**Comment by MaximeBelanger** [comment]
The ReadMe.md update site link should be also be updated.
https://github.com/mapstruct/mapstruct-eclipse/blob/master/README.md#eclipse-update-site

**Comment by filiphr** [comment]
Thanks for the information @MaximeBelanger. I just updated the link in the readme
