### ISSUE TITLE
Update-sites (release/snapshot) are down

### ISSUE THREAD

**Issue by mwerlitz** [mapstruct/mapstruct-eclipse#47]
The release (https://dl.bintray.com/mapstruct/mapstruct-eclipse-site/) and snapshot update-site seem to be down at the moment.

**Comment by filiphr** [comment]
This is a duplicate of #46 we have published the plugin to a new location (https://mapstruct.org/eclipse/). The plugin (https://marketplace.eclipse.org/content/mapstruct-eclipse-plugin) is also updated in the Eclipse marketplace. Can you please tell us where you found this links?

**Comment by mwerlitz** [comment]
I used the links in README.md, which is fixed now.
